/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author georg
 */
public class Insertar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Insertar.class.getName());

    /**
     * Creates new form Insertar
     */
    public Insertar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCentro = new javax.swing.JButton();
        btnComposicion = new javax.swing.JButton();
        btnEmpresa = new javax.swing.JButton();
        btnEnvase = new javax.swing.JButton();
        btnQuimico = new javax.swing.JButton();
        btnResiduo = new javax.swing.JButton();
        btnTipo = new javax.swing.JButton();
        btnTransporte = new javax.swing.JButton();
        btnTransportista = new javax.swing.JButton();
        btnTraslado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Insertar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        btnCentro.setText("Centro de Tratamiento");
        jPanel1.add(btnCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        btnComposicion.setText("Composicion del Quimico");
        jPanel1.add(btnComposicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        btnEmpresa.setText("Empresa");
        jPanel1.add(btnEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        btnEnvase.setText("Envase");
        jPanel1.add(btnEnvase, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        btnQuimico.setText("Quimico");
        jPanel1.add(btnQuimico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        btnResiduo.setText("Residuo");
        jPanel1.add(btnResiduo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        btnTipo.setText("Tipo de Tratamiento");
        jPanel1.add(btnTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        btnTransporte.setText("Transporte");
        jPanel1.add(btnTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        btnTransportista.setText("Transportista");
        jPanel1.add(btnTransportista, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        btnTraslado.setText("Traslado");
        jPanel1.add(btnTraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Insertar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCentro;
    private javax.swing.JButton btnComposicion;
    private javax.swing.JButton btnEmpresa;
    private javax.swing.JButton btnEnvase;
    private javax.swing.JButton btnQuimico;
    private javax.swing.JButton btnResiduo;
    private javax.swing.JButton btnTipo;
    private javax.swing.JButton btnTransporte;
    private javax.swing.JButton btnTransportista;
    private javax.swing.JButton btnTraslado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
