/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author georg
 */
public class Traslado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Traslado.class.getName());

    /**
     * Creates new form Traslado
     */
    public Traslado() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTraslado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbxEmpresa = new javax.swing.JComboBox<>();
        cbxResiduo = new javax.swing.JComboBox<>();
        cbxCentro = new javax.swing.JComboBox<>();
        cbxTratamiento = new javax.swing.JComboBox<>();
        cbxTransporte = new javax.swing.JComboBox<>();
        txfCantidad = new javax.swing.JTextField();
        txfOrigen = new javax.swing.JTextField();
        txfFechaLlegada = new javax.swing.JTextField();
        txfCosto = new javax.swing.JTextField();
        txfKilometros = new javax.swing.JTextField();
        txfFechaInicio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTraslado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTraslado.setText("Traslado");
        jPanel1.add(labelTraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 67, -1));

        jLabel1.setText("Id Empresa:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 60, 76, -1));

        jLabel2.setText("Id Residuo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 103, -1, -1));

        jLabel3.setText("Id Centro:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 58, -1));

        jLabel4.setText("Id Tratamiento:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, -1));

        jLabel5.setText("Id Transporte:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 90, -1));

        jLabel6.setText("Origen Traslado:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jLabel7.setText("Cantidad Trasladada:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jLabel8.setText("Fecha de Inicio:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        jLabel9.setText("Fecha de llegada:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jLabel10.setText("Costo:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        jLabel11.setText("Kilometros recorridos:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        cbxEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 150, -1));

        cbxResiduo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxResiduo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 150, -1));

        cbxCentro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 150, -1));

        cbxTratamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 150, -1));

        cbxTransporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 150, -1));
        jPanel1.add(txfCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 140, -1));
        jPanel1.add(txfOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 140, -1));
        jPanel1.add(txfFechaLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 150, -1));

        txfCosto.addActionListener(this::txfCostoActionPerformed);
        jPanel1.add(txfCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 150, -1));
        jPanel1.add(txfKilometros, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 150, -1));
        jPanel1.add(txfFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCostoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Traslado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxCentro;
    private javax.swing.JComboBox<String> cbxEmpresa;
    private javax.swing.JComboBox<String> cbxResiduo;
    private javax.swing.JComboBox<String> cbxTransporte;
    private javax.swing.JComboBox<String> cbxTratamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelTraslado;
    private javax.swing.JTextField txfCantidad;
    private javax.swing.JTextField txfCosto;
    private javax.swing.JTextField txfFechaInicio;
    private javax.swing.JTextField txfFechaLlegada;
    private javax.swing.JTextField txfKilometros;
    private javax.swing.JTextField txfOrigen;
    // End of variables declaration//GEN-END:variables
}
